### PR TITLE
feat: add progress indicator

### LINKED ISSUE #9: More verbose reporting during an upgrade
I ran a test with a small OrgBook wallet (~1800 credentials):

```
$ askar-upgrade --strategy dbpw --uri postgres://postgres:mysecretpassword@localhost:5433/icat_agent_wallet --wallet-name icat_agent_wallet --wallet-key key
Opening wallet with Askar...
Updating keys... 6 updated
Updating master secret(s)... 1 updated
Updating DIDs... 4 updated
Updating stored schemas... 0 updated
Updating stored credential definitions... 0 updated
Updating stored revocation registry definitions... 0 updated
Updating stored revocation registry keys... 0 updated
Updating stored revocation registry states... 0 updated
Updating stored revocation registry info... 0 updated
Updating stored credentials... 1893 updated
Closing wallet
```

There were two steps that took "awhile" - it took a few seconds (maybe 10 seconds?) before the `Opening wallet with Askar ...` message came up, and the `Updating stored credentials` step obviously took some amount of time.

Would be nice to see some "progress" messages to know what is happening during these intervals (or anywhere that *might* take longer to run)

### PR DESCRIPTION
**Pull request by dbluhm**
This PR adds a simple progress reporter that prints a line at least once per "batch" of items. This will provide (reassuring) feedback during migration of large wallets.

Resolves #9

### CODE REVIEW

**Comment by ianco** [comment]
If I don't specify `--batch-size` param I get an error:

```
$ askar-upgrade --strategy dbpw --uri postgres://postgres:mysecretpassword@localhost:5433/icat_agent_wallet --wallet-name icat_agent_wallet --wallet-key key 
Migrating items...Traceback (most recent call last):
...
  File "/Users/icostanzo/Projects/aries-acapy-wallet-upgrade/acapy_wallet_upgrade/strategies.py", line 191, in update_items
    progress.update(len(upd))
  File "/Users/icostanzo/Projects/aries-acapy-wallet-upgrade/acapy_wallet_upgrade/strategies.py", line 57, in update
    passed_intervals = ((self.count % self.interval) + amount) / self.interval
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
```

If I subsequently specify a `-batch-size` I get a different error (looks like the wallet is in a partially converted state)

**Review by ianco — CHANGES_REQUESTED** [review]
The progress indicator works great!  However I get an error unless I specify the `--batch-size` parameter (see prev comment)

This command worked great:  `$ askar-upgrade --strategy dbpw --uri postgres://postgres:mysecretpassword@localhost:5433/icat_agent_wallet --wallet-name icat_agent_wallet --wallet-key key --batch-size 100`

**Comment by dbluhm** [comment]
Thanks for the heads up; I'll shuffle around where the default batch size is being set a bit so we don't end up in a situation where the batch size is a None.

**Comment by dbluhm** [comment]
@ianco Should be fixed now! I also added a simple test to catch regressions in the script arg parsing for the batch size in the future.

**Pull request merged**
